Multiple certificates
USPCodeLabSanca/Node-Batch-Certificate-Generator pull request #11
Opened 2022-06-09 03:31 UTC by Rafael-Takano

Alterations from parserCSV, with implementation of generation of multiple cerficates

2022-06-10 20:40 UTC, nluizsoliveira requested changes

2022-06-10 20:40 UTC, nluizsoliveira commented on main.js
> +}
Gostariamos de testar se promise.all() é mais eficiente que utilizar essa abordagem. 

É possível medir tempo utilizando o módulo nativo Date(), como a seguite: 
```node

let timeStart = Date.now();

pdf.create(document, options)
    .then(res => {
        console.log(res)
        let timeEnd = Date.now();
        let totalTime = timeEnd - timeStart;
        console.log(totalTime/1000);
    })
    .catch(error => {
        console.error(error)
    });
```

Tentar implementar a tarefa acima utilizando promise.all() (https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) e medir se o tempo foi otimizado

2022-06-13 01:46 UTC, Rafael-Takano commented
I don't know if I implemented the changes correctly, but with the new file "main promises.js" the time to processes all certificates continues equal, in my understanding, the function "pdf.create()" itself is a promise, therefore the use of promise.all() don't improve the time because the function was already an asynchronous before

2022-06-13 03:20 UTC, nluizsoliveira commented
Thanks for your research! 

As you correctly stated `document.create()` is already a promise.  Your code works, but you don't need to create a promise for , all you need is to: 

```node

const promise_array = []
for(const ip of infoPath) {
	document.context = ip.info
	document.path = ip.path
	const promise = pdf.create(document, options)
        promise_array.push(promise)
}


Promise.all(promise_array)
    .then((data) => {
        console.log(data)
        let end = Date.now()
        console.log((end-start)/1000, "seconds");
    })
    .catch((error)=>{
        console.log(error)
    })

```

You're also correct when stating that multiple `document.create()` are already running async. They would be synchronous if you were creating documents inside other document's `.then()`


However there's an advantage when using `Promise.all()`: It rejects when the first error occours. Therefore if the CSV is miss-formatted in a single line, `Promise.all()` doesn't try to call `document.create()` for subsequent lines. That improves performance when the csv has bad data, as one would not have to wait for the whole process to complete. 


We could generate all certificates for correctly-formatted CSV lines, but not wrong ones, or we could stop at first error. That's a design choice.

As we have not yet sanitized inputs, I think it's better to reject everything if a line has an error (we're not sure if an error, intentional or not, specially involving \n could propagate to another lines generating certificates that seem correct but are in fact incorrec in subsequent linest)  

The  input validation/sanitizing is going to be implemented with https://joi.dev/ ,  but this will be another task/branch

You can research about Joi sanitizing if you have time/want, but let's ask if other guys want to participate too before creating a branch and implementing it 

For now use `Promise.all()`

2022-06-13 05:19 UTC, nluizsoliveira requested changes

2022-06-13 05:19 UTC, nluizsoliveira commented on main promises.js
> +console.log(end-start, "miliseconds");
Thanks for your research! 

As you correctly stated `document.create()` is already a promise.  Your code works, but you don't need to create a promise for `pdf.create(),  all you need is to: 

```node

const promise_array = []
for(const ip of infoPath) {
	document.context = ip.info
	document.path = ip.path
	const promise = pdf.create(document, options)
        promise_array.push(promise)
}


Promise.all(promise_array)
    .then((data) => {
        console.log(data)
        let end = Date.now()
        console.log((end-start)/1000, "seconds");
    })
    .catch((error)=>{
        console.log(error)
    })

```

You're also correct when stating that multiple `document.create()` are already running async. They would be synchronous if you were creating documents inside other document's `.then()`


However there's an advantage when using `Promise.all()`: It rejects when the first error occours. Therefore if the CSV is miss-formatted in a single line, `Promise.all()` doesn't try to call `document.create()` for subsequent lines. That improves performance when the csv has bad data, as one would not have to wait for the whole process to complete. 


We could generate all certificates for correctly-formatted CSV lines, but not wrong ones, or we could stop at first error. That's a design choice.

As we have not yet sanitized inputs, I think it's better to reject everything if a line has an error (we're not sure if an error, intentional or not, specially involving \n could propagate to another lines generating certificates that seem correct but are in fact incorrec in subsequent linest)  

The  input validation/sanitizing is going to be implemented with https://joi.dev/ ,  but this will be another task/branch

You can research about Joi sanitizing if you have time/want, but let's ask if other guys want to participate too before creating a branch and implementing it 

For now use `Promise.all()`

2022-06-13 05:22 UTC, nluizsoliveira commented on main promises.js
> +console.log(end-start, "miliseconds");
Also please change the target of the pull request form (main) to (certificate)
If a conflict occur and you face issues resolving it, don't hesitate on contacting me so I can help you solve it!

2022-06-15 08:33 UTC, merged